/*
 * This file is generated by jOOQ.
 */
package postgres;


import postgres.tables.Users;


/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>users</code>.
     */
    public static final Users USERS = Users.USERS;
}
