/*
 * This file is generated by jOOQ.
 */
package postgres.tables.pojos;


import java.io.Serializable;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Users implements Serializable {

    private static final long serialVersionUID = 1L;

    private final UUID id;
    private final String externalId;
    private final String name;
    private final String lastName;
    private final String email;

    public Users(Users value) {
        this.id = value.id;
        this.externalId = value.externalId;
        this.name = value.name;
        this.lastName = value.lastName;
        this.email = value.email;
    }

    public Users(
        UUID id,
        String externalId,
        String name,
        String lastName,
        String email
    ) {
        this.id = id;
        this.externalId = externalId;
        this.name = name;
        this.lastName = lastName;
        this.email = email;
    }

    /**
     * Getter for <code>users.ID</code>.
     */
    public UUID getId() {
        return this.id;
    }

    /**
     * Getter for <code>users.EXTERNAL_ID</code>.
     */
    public String getExternalId() {
        return this.externalId;
    }

    /**
     * Getter for <code>users.NAME</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Getter for <code>users.LAST_NAME</code>.
     */
    public String getLastName() {
        return this.lastName;
    }

    /**
     * Getter for <code>users.EMAIL</code>.
     */
    public String getEmail() {
        return this.email;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Users other = (Users) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.externalId == null) {
            if (other.externalId != null)
                return false;
        }
        else if (!this.externalId.equals(other.externalId))
            return false;
        if (this.name == null) {
            if (other.name != null)
                return false;
        }
        else if (!this.name.equals(other.name))
            return false;
        if (this.lastName == null) {
            if (other.lastName != null)
                return false;
        }
        else if (!this.lastName.equals(other.lastName))
            return false;
        if (this.email == null) {
            if (other.email != null)
                return false;
        }
        else if (!this.email.equals(other.email))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.externalId == null) ? 0 : this.externalId.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        result = prime * result + ((this.lastName == null) ? 0 : this.lastName.hashCode());
        result = prime * result + ((this.email == null) ? 0 : this.email.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Users (");

        sb.append(id);
        sb.append(", ").append(externalId);
        sb.append(", ").append(name);
        sb.append(", ").append(lastName);
        sb.append(", ").append(email);

        sb.append(")");
        return sb.toString();
    }
}
